Repository Yogi-Josim/2025-oss-dev-competition-server, pull requests merged in 2025-08, with the labels that each got.

#19 remove MySQL container name
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: bug

#21 rollback deploy condition
  .github/workflows/deploy.yml
Labels: bug

#27 feature/#26-create WebConfig to set CORS configuration
  src/main/java/com/example/yogijosim/config/WebConfig.java
Labels: enhancement

#34 refactor/#34-change frontend domain address and set new cors configuration
  src/main/java/com/example/yogijosim/config/WebConfig.java
  src/main/resources/templates/emergemcy-report.html
  src/main/resources/templates/periodic-report.html
Labels: enhancement

#37 hotfix : 터미널에 한글 입력이 안되어서 environment에 한글 추가
  docker-compose.yml
Labels: bug

#42 feat: add FastAPI container to docker-compose.yml
  docker-compose.yml
Labels: enhancement

#45 feature/#45-use fetch-join and set spring-server timezone
  docker-compose.yml
  src/main/java/com/example/yogijosim/schedular/IncidentProcessingScheduler.java
  src/main/java/com/example/yogijosim/schedular/MailSenderScheduler.java
  src/main/java/com/example/yogijosim/subscription/domain/SubscriptionRepository.java
  src/main/java/com/example/yogijosim/subscription/persistence/SubscriptionJpaRepository.java
  src/main/java/com/example/yogijosim/subscription/persistence/SubscriptionRepositoryImpl.java
  src/main/resources/data.sql
Labels: bug, enhancement

#46 Update README.md
  README.md
Labels: documentation
